### ISSUE TITLE
Security issue when registering new UitDB users?

### ISSUE THREAD

**Issue by netsensei** [cultuurnet/Cdb#5]
Hello,

I can create new Drupal users on a site with the Culturefeed module installed/enabled as an anonymous user even though user registration for anonymous users is disabled.

1. Go to http://mysite/culturefeed/oauth/connect/register
2. Register a new user
3. Go to user/password (Hope it's enabled)
4. Receive a password reset link on your mail
5. Login to the Drupal.

Granted, there's some effort involved. But nonetheless: I can create (in)active user accounts bypassing the 'anonymous users cannot register' permission;

Offending code:

```php
  $items['culturefeed/oauth/connect/register'] = array(
    'title' => 'Connect',
    'page callback' => 'culturefeed_oauth_connect',
    'page arguments' => array(CultureFeed::AUTHORIZE_TYPE_REGISTER),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'culturefeed.pages.inc',
  );
```
Should be:

```php
'access callback' => 'user_register_access'
```

**Comment by cyberwolf** [comment]
Not the right project to report this on.
